### ISSUE TITLE
Visa especial credit card number marked as invalid

### ISSUE THREAD

**Issue by smendozaisf** [braintree/card-validator#51]
### General information

* Library version: 4.1.0
* Browser and OS: Node.js in Windows

### Issue description

Using paypal suggested valid credit cards: https://www.paypalobjects.com/en_AU/vhelp/paypalmanager_help/credit_card_numbers.htm we receive this credit card `4222222222222` as invalid, but they said that this is a valid credit card number.

> 4222222222222
> Note : Even though this number has a different character count than the other test numbers, it is the ?
> correct and functional number.

Doing research in internet, it says that visa has a lenght of 13 or 16, but right now the package is only validating 16.

Maybe we need to add a validation for this credit card number length for visa credit cards?

**Comment by quinnjn** [comment]
Hi @smendozaisf,

13 digit Visa card numbers are no longer in circulation and we don't plan on adding it to credit-card-type. See braintree/credit-card-type/issues/43 for more details.

**Comment by Ehtishamae** [comment]
> 

I was trying to make a credit card validating app and I ran through the same error, turned out the array of individual digits extends its index to 17 while I am checking for the from second to the last and then each digit according to the validation formula.
So you need to address that problem by sett its value to 0 at index 17
