### ISSUE TITLE
Cant ID JCB and Enroute cards

### ISSUE THREAD

**Issue by teebu** [braintree/card-validator#52]
### General information

* Library version: 4.1.0

### Issue description

Can't identify these cards:

214930167048081 - enroute
3112904154980561 - JCB
180088790420118 - JCB

Using these online tool to verify validity of the above cards: 
https://names.igopaygo.com/credit-card/validate
https://www.tools4noobs.com/online_tools/credit_card_validate/

**Comment by crookedneighbor** [comment]
We use our [credit card type module](https://github.com/braintree/credit-card-type) for card type detection. 

> 214930167048081 - enroute

Looks like all enroute cards were discontinued in 1992, so we will not be adding support for it. 

> 3112904154980561 - JCB

According to our contacts with Discover, JCB cards all start with `2131`, `1800`, or `35`. If you have different information, feel free to provide us with the documentation.

> 180088790420118 - JCB

This is recognized as a JCB card. According to our contacts, JCB cards must be at least 16 characters, so this 15 digit card is potentially valid, but not valid.

```javascript
var cardValidator = require("card-validator")

var validity = cardValidator.number('180088790420118')

console.log(validity.card.type === 'jcb') // true
console.log(validity.isPotentiallyValid) // true
console.log(validity.isValid) // false
```

I'm going to close this, because I don't think there's anything actionable for the card-validator module, but if you'd like to provide documentation and open an issue on [credit card type](https://github.com/braintree/credit-card-type), go for it.

**Comment by teebu** [comment]
Thank you for your quick response, How about `869939653329358` Voyager card?

**Comment by crookedneighbor** [comment]
That seems to be a [Fuel Card](https://en.wikipedia.org/wiki/Fuel_card) and is thus not applicable for online payments.
